apiVersion: apps/v1
kind: Deployment
metadata:
  name: meeseeks
spec:
  replicas: 3
  selector:
    matchLabels:
      app: meeseeks
  template:
    metadata:
      labels:
        app: meeseeks
    spec:
      containers:
        - name: meeseeks
          image: othelloengineer/meeseeks:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: meeseeks
spec:
  selector:
    app: "meeseeks"
  ports:
    - port: 8080
      targetPort: 80
