apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter-app
  template:
    metadata:
      labels:
        app: counter-app
    spec:
      containers:
        - name: counter-app
          image: othelloengineer/counter-app
          ports:
            - containerPort: 8080
          env:
            - name: COLOR
              valueFrom:
                configMapKeyRef:
                  name: counter-app-config
                  key: color
          volumeMounts:
            - name: counter-pv
              mountPath: /app/data
      volumes:
        - name: counter-pv
          persistentVolumeClaim:
            claimName: counter-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: counter-app
spec:
  type: ClusterIP
  selector:
    app: counter-app
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: counter-app-config
data:
  color: "blue"
  counter: "99999"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: counter-pvc
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  reclaimPolicy: Retain
