apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: counter-app
  template:
    metadata:
      labels:
        app: counter-app
    spec:
      containers:
        - name: counter-app
          image: othelloengineer/counter-app
          ports:
            - containerPort: 8080
          env:
            - name: COLOR
              valueFrom:
                configMapKeyRef:
                  name: counter-app-config
                  key: color
          volumeMounts:
            - name: counter-value
              mountPath: /app/data
      volumes:
        - name: counter-value
          configMap:
            name: counter-app-config
            items:
              - key: counter
                path: counter.txt
---
apiVersion: v1
kind: Service
metadata:
  name: counter-app
spec:
  type: ClusterIP
  selector:
    app: counter-app
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: counter-app-config
data:
  color: "blue"
  counter: "99999"
