apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: counter-app
  template:
    metadata:
      labels:
        app: counter-app
    spec:
      containers:
        - name: counter-app
          image: othelloengineer/counter-app
          ports:
            - containerPort: 8080
          env:
            - name: COLOR
              value: "red"
---
apiVersion: v1
kind: Service
metadata:
  name: counter-app
spec:
  type: ClusterIP
  selector:
    app: counter-app
  ports:
    - port: 8080
      targetPort: 8080
